#!/usr/bin/env php

<?php

use App\Services\ConfigService;
use App\Services\ConsoleService;
use App\Services\FileService;
use App\Transforms\Transform;

define('SOURCE_PATH', 'https://raw.githubusercontent.com/helsingborg-stad/project-synchronizer/refs/heads/main');
define('TARGET_PATH', getcwd());
define('CONFIG_PATH', TARGET_PATH . '/ps-config.json');

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
} else {
    require_once TARGET_PATH . '/vendor/autoload.php';
}

$cmd = (object) array_merge(
    [
        'source' => SOURCE_PATH,
        'config' => CONFIG_PATH,
        'target' => TARGET_PATH,
    ],
    getopt('', [
        'source:',
        'config:',
        'target:',
        'force',
        'help',
    ]),
);

if (isset($cmd->help)) {
    echo <<<TEXT
        Usage: ps [options]
            --config <file|url>            Configuration file or URL
            --source <folder|url>          Source repository path
            --target <folder>              Target repository path
            --force                        Overwrite existing files and property values
            --help                         Display this help message
        TEXT;
    exit(1);
}

App\Module::main([
    'console' => new ConsoleService(),
    'file' => new FileService(),
    'transform' => new Transform(),
    'config' => new ConfigService($cmd),
]);
