#!/usr/bin/env php

<?php

use App\Services\ConfigService;
use App\Services\ConsoleService;
use App\Services\FileService;
use App\Transforms\Transform;

define('SOURCE_PATH', 'https://raw.githubusercontent.com/helsingborg-stad/project-synchronizer/refs/heads/main');
define('TARGET_PATH', getcwd());
define('CONFIG_PATH', TARGET_PATH . '/ps-config.json');

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
} else {
    require_once TARGET_PATH . '/vendor/autoload.php';
}

$cmd = (object) array_merge(
    [
        'source' => SOURCE_PATH,
        'target' => TARGET_PATH,
        'config' => CONFIG_PATH,
    ],
    getopt('', [
        'source:',
        'target:',
        'config:',
        'init',
        'force',
        'help',
    ]),
);

$services = [
    'config' => new ConfigService($cmd),
    'console' => new ConsoleService(),
    'file' => new FileService(),
    'transform' => new Transform(),
];

if (isset($cmd->help)) {
    $services['console']->writeLn(<<<TEXT
    Usage: ps [options]
        --source <folder|url>          Source repository path
        --target <folder>              Target repository path
        --config <file|url>            Configuration file or URL
        --init                         Create a new configuration file at target path
        --force                        Overwrite existing files and property values
        --help                         Display this help message
    TEXT);
    exit(1);
}

if (isset($cmd->init)) {
    try {
        $config->saveConfig(new FileService());
        $services['console']->writeLn("Configuration file created at {$config->getConfigPath()}");
        exit(0);
    } catch (\Exception $e) {
        $services['console']->writeLn($e->getMessage());
        exit(1);
    }
}

App\Module::main($services);
